pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "build phase"
            }
        }
        stage('Test'){
            steps {
                echo "Test phase"
                junit 'reports/**/*.xml'
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploy phase"
            }
        }
    }
}